### ISSUE TITLE
Does the input select command work?

### ISSUE THREAD

**Issue by ardemk** [pepitooo/naim-uniti-remote#1]
Everything in the code works for my Uniti Atom (thank you for this!) aside from the input selection. 

Example of a PUT request to select the Analog 1 input: 
http://IPofmyUniti:15081/inputs/ana1?cmd=select 

Any idea why nothing is happening?

Thank you very much for your help.

A fellow multi-hardware user who needs a universal remote ;)

**Comment by pepitooo** [comment]
It have to be a [GET](https://github.com/pepitooo/naim-uniti-remote/blob/c56185d3d471c67739fdd94164d7d49977b9b2d5/naim-uniti.py#L74) request. To control the naim it's a mix of PUT and GET, I remember spending some time to understand why it was not working the first time.

By running this command on my mac from a terminal it change the source.
$ curl "http://naimip:15081/inputs/ana1?cmd=select"
{
  "code": 0,
  "reason": "OK"
}

Be sure the analog input is enable via Naim app, but should not block the source selection.

**Comment by ardemk** [comment]
Thank you!
The GET command did the trick.
You're a lifesaver 👍 

By any chance, do you have the list of the API endpoints? This can be shared privately.
I have some ideas that could enrich your code with additional settings interesting in a Home Theater environment provided the endpoints exist (turn off the display during movie playback or reduce the gain in AV bypass mode to limit the hiss when using a receiver as a pre-amp).

Cheers!

**Comment by pepitooo** [comment]
I'm sorry but what I did was to reverse engineer the Naim app protocol for what I needed:
- power on/off
- change source
- changing volume

If you want more you will need to intercept the network traffic when you change setting with the Naim app.

Maybe will not be able to do thing you can do with the remote, because the remote is not communicating through the network but via RF. Only change via the Naim app can be reproduce.

**Comment by ardemk** [comment]
I understand. Thank you very much for these answers and your responsiveness.
